// This file is part of AbstractCode.
// 
// AbstractCode is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// AbstractCode is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Lesser General Public License for more details.
// 
// You should have received a copy of the GNU Lesser General Public License
// along with AbstractCode.  If not, see <http://www.gnu.org/licenses/>.
// 

namespace AbstractCode.Ast.CSharp
{
    // Capital names are being used to distinguish easily between tokens and grammar definitions in the C# grammar.
    // ReSharper disable InconsistentNaming
    public enum CSharpAstTokenCode
    {
        EOF,
        NONE,
        ERROR,
        NEWLINE,

        FIRST_KEYWORD,
        ABSTRACT,
        AS,
        ADD,
        BASE,
        BOOL,
        BREAK,
        BYTE,
        CASE,
        CATCH,
        CHAR,
        CHECKED,
        CLASS,
        CONST,
        CONTINUE,
        DECIMAL,
        DEFAULT,
        DELEGATE,
        DO,
        DOUBLE,
        ELSE,
        ENUM,
        EVENT,
        EXPLICIT,
        EXTERN,
        FALSE,
        FINALLY,
        FIXED,
        FLOAT,
        FOR,
        FOREACH,
        GOTO,
        IF,
        IMPLICIT,
        IN,
        INT,
        INTERFACE,
        INTERNAL,
        IS,
        LOCK,
        LONG,
        NAMESPACE,
        NEW,
        NULL,
        OBJECT,
        OPERATOR,
        OUT,
        OVERRIDE,
        PARAMS,
        PRIVATE,
        PROTECTED,
        PUBLIC,
        READONLY,
        REF,
        RETURN,
        REMOVE,
        SBYTE,
        SEALED,
        SHORT,
        SIZEOF,
        STACKALLOC,
        STATIC,
        STRING,
        STRUCT,
        SWITCH,
        THIS,
        THROW,
        TRUE,
        TRY,
        TYPEOF,
        UINT,
        ULONG,
        UNCHECKED,
        UNSAFE,
        USHORT,
        USING,
        VIRTUAL,
        VOID,
        VOLATILE,
        WHERE,
        WHILE,
        ARGLIST,
        PARTIAL,
        ARROW,
        FROM,
        JOIN,
        ON,
        EQUALS,
        SELECT,
        GROUP,
        BY,
        LET,
        ORDERBY,
        ASCENDING,
        DESCENDING,
        INTO,
        INTERR_NULLABLE,
        EXTERN_ALIAS,
        REFVALUE,
        REFTYPE,
        MAKEREF,
        ASYNC,
        AWAIT,
        INTERR_OPERATOR,
        WHEN,
        INTERPOLATED_STRING,
        INTERPOLATED_STRING_END,
        YIELD,
        
        GET,
        SET,
        LAST_KEYWORD,

        OPEN_BRACE,
        CLOSE_BRACE,
        OPEN_BRACKET,
        CLOSE_BRACKET,
        OPEN_PARENS,
        CLOSE_PARENS,
        DOT,
        COMMA,
        COLON,
        SEMICOLON,
        TILDE,
        PLUS,
        MINUS,
        BANG,
        ASSIGN,
        OP_LT,
        OP_GT,
        BITWISE_AND,
        BITWISE_OR,
        STAR,
        PERCENT,
        DIV,
        CARRET,
        INTERR,

        DOUBLE_COLON,
        OP_INC,
        OP_DEC,
        OP_SHIFT_LEFT,
        OP_SHIFT_RIGHT,
        OP_LE,
        OP_GE,
        OP_EQUALS,
        OP_NOTEQUALS,
        OP_AND,
        OP_OR,
        OP_MULT_ASSIGN,
        OP_DIV_ASSIGN,
        OP_MOD_ASSIGN,
        OP_ADD_ASSIGN,
        OP_SUB_ASSIGN,
        OP_SHIFT_LEFT_ASSIGN,
        OP_SHIFT_RIGHT_ASSIGN,
        OP_AND_ASSIGN,
        OP_XOR_ASSIGN,
        OP_OR_ASSIGN,
        OP_PTR,
        OP_COALESCING,
        OP_GENERICS_LT,
        OP_GENERICS_LT_DECL,
        OP_GENERICS_GT,
        LITERAL,
        IDENTIFIER,
        OPEN_PARENS_LAMBDA,
        OPEN_PARENS_CAST,
        GENERIC_DIMENSION,
        DEFAULT_COLON,
        OPEN_BRACKET_EXPR,
    }
    // ReSharper restore InconsistentNaming
}